"""empty message

Revision ID: 1b7ce84f6d78
Revises: f21f69eef6f4
Create Date: 2022-01-22 04:37:30.875081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b7ce84f6d78'
down_revision = 'f21f69eef6f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'encoding', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'encoding', type_='unique')
    # ### end Alembic commands ###
