"""empty message

Revision ID: 6f17eddd81cf
Revises: 53e81c4c49bc
Create Date: 2021-12-01 19:51:08.659227

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f17eddd81cf'
down_revision = '53e81c4c49bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'check_out_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'check_out_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
